

//Generated for platform: x64

// This code was generated by a script. Any changes made manually will be lost
// the next time this code is regenerated.

using System.Reflection;
using System.Resources;

// Compute version values

//Build nr: 3435

// General Information
[assembly: AssemblyTitle("mRemoteNG")]
[assembly: AssemblyDescription("Multi-Remote Connection Manager")]
[assembly: AssemblyConfiguration("x64")]
[assembly: AssemblyCompany("mRemoteNG")]
[assembly: AssemblyProduct("mRemoteNG")]
[assembly: AssemblyCopyright("(c) 2026 mRemoteNG")]
[assembly: AssemblyTrademark("mRemoteNG")]
[assembly: AssemblyCulture("")]

// Version information
[assembly: AssemblyVersion("1.82.0.3435")]
[assembly: AssemblyFileVersion("1.82.0.3435")]
[assembly: NeutralResourcesLanguageAttribute("en-US")]
[assembly: AssemblyInformationalVersion("1.82.0-beta.3 (Pre-release 3435) x64")]
