//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mRemoteNG.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class OptionsTerminalPage : global::System.Configuration.ApplicationSettingsBase {

        private static OptionsTerminalPage defaultInstance = ((OptionsTerminalPage)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OptionsTerminalPage())));

        public static OptionsTerminalPage Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cascadia Mono, Consolas, monospace")]
        public string TerminalFontFamily {
            get {
                return ((string)(this["TerminalFontFamily"]));
            }
            set {
                this["TerminalFontFamily"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int TerminalFontSize {
            get {
                return ((int)(this["TerminalFontSize"]));
            }
            set {
                this["TerminalFontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Follow")]
        public string TerminalColorScheme {
            get {
                return ((string)(this["TerminalColorScheme"]));
            }
            set {
                this["TerminalColorScheme"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int TerminalScrollback {
            get {
                return ((int)(this["TerminalScrollback"]));
            }
            set {
                this["TerminalScrollback"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TerminalCtrlVPastes {
            get {
                return ((bool)(this["TerminalCtrlVPastes"]));
            }
            set {
                this["TerminalCtrlVPastes"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbTerminalPageInOptionMenu {
            get {
                return ((bool)(this["cbTerminalPageInOptionMenu"]));
            }
            set {
                this["cbTerminalPageInOptionMenu"] = value;
            }
        }
    }
}
